# Generated by Django 4.0.5 on 2022-06-28 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('statement', models.CharField(max_length=2000)),
                ('difficulty', models.CharField(max_length=200)),
                ('solved_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Test_cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_case', models.CharField(max_length=200)),
                ('output_case', models.CharField(max_length=200)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.TimeField(null=True)),
                ('verdict', models.CharField(max_length=200)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.problem')),
            ],
        ),
    ]
